### ISSUE TITLE
Threshold value

### ISSUE THREAD

**Issue by ieva-raminta** [cognitiveailab/tg2021task#7]
Hi, it seems the threshold in the evaluation script is set at 0 (line 67: "rating_threshold = 0") but in the comment it says 2 (line 149: "# Only consider relevance scores greater than 2"). I was wondering which value is the correct one to be used? Thanks!

**Comment by mValentino91** [comment]
Hi, the correct value to use is rating_threshold = 0. We will correct the comment in line 149. Thank you very much for reporting the issue!
